[lsp]
pubkey = ""
address = "127.0.0.1:9737"
auth = "00000000000000000000000000000000"

[node]
network = "signet"
chain_source_url = "https://mutinynet.com/api/"
data_dir = ".data"
alias = "lsp"
port = 9737

[stable_channel_defaults]
expected_usd = 20.0
sc_dir = ".data"

resources = ["src/config.toml"]